CREATE TABLE kimball.dim_date (
    date_sk         INTEGER PRIMARY KEY,
    full_date       DATE UNIQUE,
    day             SMALLINT NOT NULL,
    day_of_week     SMALLINT NOT NULL,
    day_name        VARCHAR(20) NOT NULL,
    month           SMALLINT NOT NULL,
    month_name      VARCHAR(20) NOT NULL,
    quarter         SMALLINT NOT NULL,
    year            SMALLINT NOT NULL,
    load_timestamp  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kimball.dim_customer (
    customer_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id               VARCHAR(32) NOT NULL UNIQUE,
    customer_unique_id        VARCHAR(32) NOT NULL,
    customer_zip_code_prefix  INTEGER,
    customer_city             VARCHAR(100),
    customer_state            VARCHAR(2),
    load_timestamp            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kimball.dim_order_status (
    order_status_sk  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_status     VARCHAR(30) NOT NULL UNIQUE,
    load_timestamp   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kimball.dim_product (
    product_sk             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id             VARCHAR(32) NOT NULL UNIQUE,
    product_category_name  VARCHAR(100),
    load_timestamp         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE kimball.dim_seller (
    seller_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id               VARCHAR(32) NOT NULL UNIQUE,
    seller_zip_code_prefix  INTEGER,
    seller_city             VARCHAR(100),
    seller_state            VARCHAR(2),
    load_timestamp          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);