/*
 * Criação das dimensões do Data Mart — Estado T0
 *
 * O Data Mart é derivado do Raw Vault e deve ser
 * funcionalmente equivalente ao modelo Kimball T0.
 *
 * Dimensões:
 * - dim_date
 * - dim_customer
 * - dim_order_status
 * - dim_product
 * - dim_seller
 */


/* ============================================================
 * 1. DIM_DATE
 * ============================================================
 */

CREATE TABLE IF NOT EXISTS data_mart.dim_date (

    date_sk INTEGER PRIMARY KEY,

    full_date DATE UNIQUE,

    day SMALLINT NOT NULL,

    day_of_week SMALLINT NOT NULL,

    day_name VARCHAR(20) NOT NULL,

    month SMALLINT NOT NULL,

    month_name VARCHAR(20) NOT NULL,

    quarter SMALLINT NOT NULL,

    year SMALLINT NOT NULL,

    load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* ============================================================
 * 2. DIM_CUSTOMER
 * ============================================================
 *
 * Grão:
 * uma linha por customer_id
 *
 * Observação:
 * no Raw Vault, hub_customer possui grão customer_unique_id.
 *
 * Aqui reconstruímos o grão analítico customer_id utilizando:
 *
 * hub_customer
 * +
 * link_order_customer
 * +
 * sat_order_customer
 * ============================================================
 */

CREATE TABLE IF NOT EXISTS data_mart.dim_customer (

    customer_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_id VARCHAR(32) NOT NULL UNIQUE,

    customer_unique_id VARCHAR(32) NOT NULL,

    customer_zip_code_prefix INTEGER,

    customer_city VARCHAR(100),

    customer_state VARCHAR(2),

    load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* ============================================================
 * 3. DIM_ORDER_STATUS
 * ============================================================
 *
 * Grão:
 * uma linha por order_status
 *
 * Origem lógica:
 * sat_order.order_status
 * ============================================================
 */

CREATE TABLE IF NOT EXISTS data_mart.dim_order_status (

    order_status_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_status VARCHAR(30) NOT NULL UNIQUE,

    load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* ============================================================
 * 4. DIM_PRODUCT
 * ============================================================
 *
 * Grão:
 * uma linha por product_id
 *
 * Origem lógica:
 * hub_product
 * +
 * sat_product
 *
 * T0:
 * sem tratamento histórico específico de M3.
 * ============================================================
 */

CREATE TABLE IF NOT EXISTS data_mart.dim_product (

    product_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id VARCHAR(32) NOT NULL UNIQUE,

    product_category_name VARCHAR(100),

    load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


/* ============================================================
 * 5. DIM_SELLER
 * ============================================================
 *
 * Grão:
 * uma linha por seller_id
 *
 * Origem lógica:
 * hub_seller
 * +
 * sat_seller
 * ============================================================
 */

CREATE TABLE IF NOT EXISTS data_mart.dim_seller (

    seller_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    seller_id VARCHAR(32) NOT NULL UNIQUE,

    seller_zip_code_prefix INTEGER,

    seller_city VARCHAR(100),

    seller_state VARCHAR(2),

    load_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);